import type { Question } from './types';

// ==========================================
// EDIT THESE TO MATCH YOUR RELATIONSHIP DETAILS! 💕
// ==========================================
export const RELATIONSHIP_CONFIG = {
  // Enter your WhatsApp phone number with country code (no '+' or spaces, e.g. '919876543210' for India)
  // When your partner finishes the game, they can click a button to send all answers directly to this number!
  whatsappNumber: '', 
  
  firstTalkDate: '2026-03-27', // YYYY-MM-DD
  whoFellFirst: 'Aishu', // 'Prago' or 'Aishu'
  whoStartsArguments: 'Aishu', // 'Prago' or 'Aishu'
  nicknamesLiked: ['baby', 'babe', 'cutie', 'kanmani', 'kunju', 'chelow', 'kutti'],
  greenFlags: ['caring', 'smile', 'cooking', 'listening', 'kindness', 'everything', 'eyes', 'patience'],
  redFlags: ['none', 'nothing', 'sleeping', 'eating my food', 'being too cute', 'overthinking'],
  firstDateOutfit: ['black top and jeans'],
  firstMessage: 'hey',
  mostUsedEmoji: '🫂',
};

export const QUESTIONS: Question[] = [
  {
    id: 1,
    type: 'date',
    question: 'When did we first met? 🗓️',
    placeholder: 'Select the date...',
    hint: `Hint: It was a beautiful day around March 2026!)`,
    skipGrading: true,
    successMessage: 'A beautiful date that changed everything! 🗓️✨',
  },
  {
    id: 2,
    type: 'choice',
    question: 'Who fell first? 💘',
    options: ['Prago 🙋‍♂️', 'Aishu 🙋‍♀️'],
    hint: 'Think about who was sliding into whose DMs first! 😉',
    skipGrading: true,
    successMessage: 'Aww, falling first is the best part! 💘',
  },
  {
    id: 3,
    type: 'choice',
    question: 'Who starts arguments over absolutely nothing? 😤',
    options: ['Prago 🤷‍♂️', 'Aishu 🤷‍♀️', 'The Cat 🐱'],
    hint: 'Be honest... who gets grumpy when they are hungry? 🍕',
    skipGrading: true,
    successMessage: "Aha! Let's agree to disagree. 😤🍕",
  },
  {
    id: 4,
    type: 'choice',
    question: "What's my fav food? 😋",
    options: ['Biriyani 🍛', 'Fried Rice 🍚', 'Pizza 🍕', 'Salad 🥗'],
    hint: 'It is flavorful, has spices, and is pure happiness in a plate!',
    skipGrading: true,
    successMessage: 'Biriyani is always correct! 😋🍛',
  },
  {
    id: 5,
    type: 'choice',
    question: "What's my dream vacation? ✈️",
    options: ['Paris 🗼', 'Switzerland 🏔️', 'Ladakh 🏍️', 'Home with you 🏡'],
    hint: 'The city of love! (Though home with you is a close second... 🥺)',
    skipGrading: true,
    successMessage: 'Paris! The city of love. ✈️🗼',
  },
  {
    id: 6,
    type: 'text',
    question: 'What nickname do you secretly like calling me? 🤫',
    placeholder: 'Type nickname here...',
    hint: 'Examples: baby, cutie, love... (Write whatever nickname you like! 🥰)',
    skipGrading: true,
    successMessage: 'Aww! That is such a sweet nickname. I love it! 🥺❤️',
  },
  {
    id: 7,
    type: 'text',
    question: "What's my green flag? 💚",
    placeholder: 'Type a green flag...',
    hint: 'Is it my smile, how I listen, how caring I am, or just everything? 🥰',
    skipGrading: true,
    successMessage: "Thank you for answering! You're my green flag too. 💚",
  },
  {
    id: 8,
    type: 'text',
    question: "What's my biggest red flag? 🚩",
    placeholder: 'Type a red flag...',
    hint: 'Be honest! Sleeping? Eating my food? Being too cute? 🤫',
    skipGrading: true,
    successMessage: 'Hey! That is NOT a red flag... but okay, I will let you have this one! 🚩😅',
  },
  {
    id: 9,
    type: 'text',
    question: 'What was I wearing on our first date? 👗',
    placeholder: 'I think you remember..',
    hint: 'Think colors... (Write whatever you remember! 😉)',
    skipGrading: true,
    successMessage: 'Yes, I remember that day clearly. You looked amazing! ✨',
  },
  {
    id: 10,
    type: 'text',
    question: "What's the first message I sent you? 💬",
    placeholder: 'Type message...',
    hint: 'Hint: A classic greeting or introduction (Write what you recall! 💬)',
    skipGrading: true,
    successMessage: 'That first message started everything. 🥰💬',
  },
  {
    id: 11,
    type: 'emoji',
    question: 'Which emoji do I use the most? 🎭',
    options: ['🫂', '😭', '🥺', '🤣', '😘', '🥰', '🤡', '🙄'],
    hint: 'It represents my infinite love for you! 🫂',
    skipGrading: true,
    successMessage: 'Yes, the hugging emoji is my favorite! 🫂❤️',
  },
  {
    id: 12,
    type: 'would-you-rather',
    question: 'Would you rather: 🧐',
    options: ['Go one month without kissing me 😢', 'Go one month with your phone switched off 📱'],
    correctAnswer: 'Go one month with your phone switched off 📱',
    skipGrading: true,
    successMessage: 'Phone switched off it is! Kisses are mandatory. 💋',
  },
  {
    id: 13,
    type: 'potato',
    question: 'If I became a potato 🥔, would you:',
    options: ['Fry me 🍟', 'Boil me 🍲', 'Marry me 💍'],
    correctAnswer: 'Marry me 💍',
    hint: 'The other two options might run away from you... literally! 🏃‍♂️',
    skipGrading: true,
    successMessage: 'Marry me! The correct answer. 💍🥔',
  },
  {
    id: 14,
    type: 'cutest',
    question: 'Who is the cutest in this relationship? 👑',
    options: ['Aishu 🥺', 'Also Aishu 🥰', 'Still Aishu 👑', 'There is no other correct answer 💖'],
    correctAnswer: 'There is no other correct answer 💖',
    hint: 'Hint: All options are technically correct, but one is the absolute truth! 😉',
    skipGrading: true,
    successMessage: 'We are both the cutest! 🥰👑',
  },
  {
    id: 15,
    type: 'text',
    question: 'How many kisses do you owe me right now? 💋',
    placeholder: 'Type number or answer...',
    hint: 'Give me a big number! 💋',
    skipGrading: true,
    successMessage: "I'll hold you to that! 💋😉",
  },
  {
    id: 16,
    type: 'text',
    question: "What's the first thing you'd do if we were alone for 24 hours? 😉",
    placeholder: 'Be honest... 🙈',
    hint: 'Cuddles? Movie marathon? Dinner date?',
    skipGrading: true,
    successMessage: 'Ooh, sounds like a plan! 🙈💖',
  },
  {
    id: 17,
    type: 'text',
    question: 'Which outfit of mine drives you crazy? 🔥',
    placeholder: 'Describe the outfit...',
    hint: 'Traditional? Casual? The first date look?',
    skipGrading: true,
    successMessage: "Good choice! I'll wear that more often. 🔥😏",
  },
  {
    id: 18,
    type: 'choice',
    question: 'Who usually starts the flirting? 💘',
    options: ['Prago 🤭', 'Aishu 😏', 'Both of us 💖', 'None, we are too shy 🙈'],
    hint: 'Think about who sends the first flirty meme!',
    skipGrading: true,
    successMessage: 'Aha! I knew it. 😉',
  },
  {
    id: 19,
    type: 'text',
    question: 'When did you first realize you liked me? ⏳',
    placeholder: 'Describe that moment...',
    hint: 'Was it a specific text, a phone call, or our first meet?',
    skipGrading: true,
    successMessage: 'Aww, that is so sweet. My heart is melting... 🥺❤️',
  },
  {
    id: 20,
    type: 'text',
    question: "What's one thing I do that gives you butterflies? 🦋",
    placeholder: 'Type here...',
    hint: 'Is it my eye contact, my voice, or how I laugh?',
    skipGrading: true,
    successMessage: "Really? I'll keep doing it then! 🦋🥰",
  },
  {
    id: 21,
    type: 'text',
    question: 'If we had a weekend with no phones, what would you plan for us? 🏡',
    placeholder: 'Type details...',
    hint: 'Cooking together, playing board games, stargazing?',
    skipGrading: true,
    successMessage: 'That sounds like the perfect weekend! 🏡💕',
  },
  {
    id: 22,
    type: 'choice',
    question: "If I said \"Come here,\" what's your first reaction? 🏃",
    options: ['🏃 Run to you', '😳 Blush', '🙈 Ask why', '❤️ "Already on my way."'],
    hint: 'Pick the one that represents your speed! 💨',
    skipGrading: true,
    successMessage: 'Hehe, you better be! 🏃‍♂️💨',
  },
  {
    id: 23,
    type: 'text',
    question: 'If you had to describe me in three words, what would they be? ✍️',
    placeholder: 'Three words...',
    hint: 'e.g. Cute, caring, funny...',
    skipGrading: true,
    successMessage: 'Aww! Those are the best three words ever. 🥺💖',
  },
  {
    id: 24,
    type: 'text',
    question: "What's one thing I do that makes your heart melt every single time? 🫠",
    placeholder: 'Describe here...',
    hint: 'Is it how I look at you, or a cute text I send?',
    skipGrading: true,
    successMessage: 'You are too sweet to me! Melted... 🫠❤️',
  },
  {
    id: 25,
    type: 'text',
    question: 'If you had 30 seconds to make me blush, what would you say? 😳',
    placeholder: 'What would you say...',
    hint: 'Say something romantic or teasing! 😉',
    skipGrading: true,
    successMessage: 'Omg, you succeeded! I am blushing right now. 😳💕',
  },
];
